# Generated by Django 3.1.2 on 2020-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_spotting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='spotting',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='bird',
            name='habitats',
            field=models.ManyToManyField(to='main_app.Habitat'),
        ),
    ]
